services:
  script-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret-key-change-this}
      - CONFIG_PATH=${CONFIG_PATH:-/app/data/config.json}
      - SCRIPTS_DIR=${SCRIPTS_DIR:-/app/scripts}
