services:
  script-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-key-change-this
      - CONFIG_PATH=/app/data/config.json
      - SCRIPTS_DIR=/app/scripts
